language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - postgresql
script:
  - pytest --cov=api tests/ # or py.test for Python versions 3.5 and below
after_script:
  - coveralls